### ISSUE TITLE
Install target instead of post-build copy steps

### ISSUE THREAD

**Issue by retifrav** [konovalov-aleks/reSL#5]
This is not really an issue or a problem, because things do work as they are. So if you don't like the following suggestion or think that it is redundant, that would be totally understandable.

So, in general, CMake projects can have a so-called [install target](https://cmake.org/cmake/help/latest/command/install.html), which is intended for preparing the build artifacts for deployment. It is mostly beneficial for libraries (*for making CMake packages*), however it is often used for executables too.

For example, instead of copying game resources [like this](https://github.com/konovalov-aleks/reSL/blob/b76ebc5a3572376fda38172b1d7ccd85241b2fc8/CMakeLists.txt#L132-L153):

``` cmake
add_custom_command(
    TARGET resl
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        ${CMAKE_CURRENT_SOURCE_DIR}/resources/play.7
        $<TARGET_FILE_DIR:resl>/play.7
    # ...and so on
```

it can be done like this:

``` cmake
set(resource_files
    resources/play.7
    resources/GAMEOVER.7
    resources/demo_a
    resources/captions.7
    resources/poster.7
    resources/RULES.TXT
)

install(FILES
    ${resource_files}
    DESTINATION ${CMAKE_INSTALL_BINDIR} # or whereever the executable is installed to
)
```

Another thing (*although not something to be performed with `install()`*) is the [SDL's DLL deployment](https://github.com/konovalov-aleks/reSL/blob/b76ebc5a3572376fda38172b1d7ccd85241b2fc8/CMakeLists.txt#L156-L160). In case of a statically linked SDL it will copy that binary too (*`SDL2-static.lib`*), which is obviously redundant. A better(?) although more complex way to handle this would be something like that:

``` cmake
if("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
    # locate DLLs, if there are any (might also discover some redundant ones)
    set(RUNTIME_DLL_SET $<BOOL:$<TARGET_RUNTIME_DLLS:${CMAKE_PROJECT_NAME}>>)
    set(COPY_COMMAND
        ${CMAKE_COMMAND} -E copy_if_different
        $<TARGET_RUNTIME_DLLS:${CMAKE_PROJECT_NAME}>
        ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}
    )
    add_custom_command(
        TARGET ${CMAKE_PROJECT_NAME}
        POST_BUILD
        COMMAND "$<${RUNTIME_DLL_SET}:${COPY_COMMAND}>"
        COMMAND_EXPAND_LISTS
        COMMENT "Copying runtime dependencies (DLLs)"
    )
endif()
```

That way it will also take care of other possible runtime dependencies (*should you ever have more of those in future*), not just one hardcoded SDL.

I've actually made a vcpkg port for reSL in my personal registry, you can take a look at the [full patch](https://github.com/retifrav/vcpkg-registry/blob/d28521a91fd3dbe7460a6c60baa302445a11cf9b/ports/resl/001-non-development-build-and-installation.patch) there.

If you would like to, I could probably prepare a pull request for your repository (*with just the installation parts*). Otherwise, feel free to cherry-pick any changes that you might like in there, I won't mind at all.

**Comment by konovalov-aleks** [comment]
Nice catch! Thank you! Will improve this

**Comment by konovalov-aleks** [comment]
I tried to replace the custom copy command with an install command. But I found that in this case the resource files are not copied during the build (it's required to manually call the "install" script), which makes the development process inconvenient (for example, if you just generate the project and run it in Xcode, the game does not start due to lack of resources, you have to copy them manually).

So, I decided to keep both options - I copy the resources to the build directory, and I also implemented the install script => now it's possible to install the game into the system via "make install" call.

I also replaced the script that copies DLL dependencies with your version. This looks and works better, thank you for the advice!

PR: https://github.com/konovalov-aleks/reSL/pull/9
